Phase 2
ashwin8448/hrmApp pull request #2
Opened 2023-10-17 12:28 UTC by ashwin8448

2023-10-17 17:04 UTC, dineshkumarrajaguru requested changes

2023-10-17 17:04 UTC, dineshkumarrajaguru commented on js/handlers.js
> +            <button type="button" class="skill-close"><img data-skill="${target.value}" src="./assets/images/close_button_icon.svg" alt=""></button>
Give alt messages wherever you are using images.

2023-10-18 11:58 UTC, ashwin8448 commented on data/data.json
> +    "1000": {
Right now I am storing employee details as an array of object. So this id as key is not useful. I am planning to use firebase for storing data. When storing in firebase I am planning to set id as key.

2023-10-18 12:00 UTC, ashwin8448 commented on index.html
> +            data-mode="new"
I added a custom attribute for form called "mode". The same form is used to add and edit details. In add mode a new form is displayed and in edit mode a prefilled form is opened.

2023-10-18 12:03 UTC, ashwin8448 commented on index.html
> +                  <p class="error-placeholder">Error placeholder</p>
A p tag has been added for displaying validation errors. It is hidden by default. Since it is hidden the form takes up the necessary space required to display any error during validation. If this placeholder is not used then the height of form will increase instantly as new errors are displayed.

2023-10-20 09:49 UTC, dineshkumarrajaguru commented on index.html
> +                    title="Click to sort"
Click to sort based on name

2023-10-20 09:49 UTC, dineshkumarrajaguru commented on js/state.js
> +  lastId: "1003",
Why is this hard coded?

2023-10-20 10:12 UTC, ashwin8448 commented on js/state.js
> +  lastId: "1003",
Employee ID is autogenerated starting from 1000. lastId stores the last employee ID that was assigned to any employee. As I have already hard coded details of 4 employees in the storage I have set lastId to 1003.

2023-10-20 10:33 UTC, ashwin8448 commented on index.html
> +                    <option value="Intern">Intern</option>
I made a custom element for drop down. Now I am adding events to it. After this I will load the options from JavaScript.

2023-10-20 10:34 UTC, ashwin8448 commented on js/edit.js
> +    newEmployeeForm["fname"].value = filteredEmployees[0].fname;
This code was used to prefill the edit employee form. Now I replaced it with a for loop.

2023-10-24 05:32 UTC, merged