Phase 3
ashwin8448/hrmApp pull request #3
Opened 2023-10-20 05:22 UTC by ashwin8448

# hrmApp

**New features:**
* Pagination addded to web application.

**Storage:**
* The application uses localStorage.

**Upcoming features:**
* Search skills in the filter box.
* Skills field in new employee form will be searchable.

2023-10-20 09:04 UTC, vipinmsqburst requested changes

2023-10-20 09:12 UTC, ashwin8448 commented on js/main.js
> +let employeesDb = [
Now I am using localStorage for handling data. So I hard coded few employee details to check whether my functionalities are working correctly.

2023-10-20 09:23 UTC, vipinmsqburst commented on js/main.js
> +let employeesDb = [
Ok

2023-10-24 08:05 UTC, dineshkumarrajaguru requested changes

2023-10-24 08:05 UTC, dineshkumarrajaguru commented on js/handlers.js
> +        console.log(target.value)
Please remove console.log

2023-10-24 08:05 UTC, dineshkumarrajaguru commented on js/handlers.js
> +  console.log(tempEmployee.skills)
Remove console.

2023-10-24 08:52 UTC, ashwin8448 commented on js/displayTable.js
> +  setTotalPages(filteredEmployees.length);
filteredEmployees.length is used to calculate the total number of pages.

2023-10-24 11:45 UTC, ashwin8448 commented on js/edit.js
> +  filterEmployees();
Modified filterEmployees to filter a given array and return filtered array.

2023-10-25 07:12 UTC, dineshkumarrajaguru commented on js/edit.js
> +      employee.fname + " " + employee.lname;
In future if someone changes the order of HTML element then we will end up with wrong data mapping.

2023-10-25 15:37 UTC, merged